// ─────────────────────────────────────────────
// Mock Data for Admin Collection UI
// ─────────────────────────────────────────────

import type {
  CollectionLog,
  CollectionSchedule,
  CollectionSettings,
  ConnectorHealthStatus,
} from "./types";

// ── Default Collection Settings ──

export const DEFAULT_SETTINGS: CollectionSettings = {
  globalEnabled: true,
  defaultFrequency: "daily",
  defaultRetryPolicy: "exponential",
  defaultMaxRetries: 3,
  devMode: true,
  mockFallback: true,
  rateLimitPerMinute: 60,
  dataRetentionDays: 90,
};

// ── Mock Collection Logs ──

const now = Date.now();
const hour = 3600000;

export const MOCK_LOGS: CollectionLog[] = [
  {
    id: "log-001",
    jobId: "job-001",
    type: "channel",
    platform: "youtube",
    target: "UC_mock_001",
    connectorId: "youtube-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour * 2).toISOString(),
    endedAt: new Date(now - hour * 2 + 450).toISOString(),
    durationMs: 450,
    itemCount: 1,
    metadata: {},
  },
  {
    id: "log-002",
    jobId: "job-002",
    type: "content",
    platform: "youtube",
    target: "UC_mock_001",
    connectorId: "youtube-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour * 2 + 500).toISOString(),
    endedAt: new Date(now - hour * 2 + 1200).toISOString(),
    durationMs: 700,
    itemCount: 5,
    metadata: {},
  },
  {
    id: "log-003",
    jobId: "job-003",
    type: "comment",
    platform: "instagram",
    target: "ig_brand_official",
    connectorId: "instagram-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour * 3).toISOString(),
    endedAt: new Date(now - hour * 3 + 800).toISOString(),
    durationMs: 800,
    itemCount: 12,
    metadata: {},
  },
  {
    id: "log-004",
    jobId: "job-004",
    type: "mention",
    platform: "x",
    target: "소셜 분석",
    connectorId: "x-mock",
    status: "failed",
    errorMessage: "Bearer token not configured",
    userMessage:
      "X API 인증 토큰이 설정되지 않았습니다. 환경 변수를 확인해주세요.",
    retryCount: 3,
    startedAt: new Date(now - hour * 4).toISOString(),
    endedAt: new Date(now - hour * 4 + 200).toISOString(),
    durationMs: 200,
    itemCount: 0,
    metadata: {},
  },
  {
    id: "log-005",
    jobId: "job-005",
    type: "content",
    platform: "tiktok",
    target: "tiktok_brand_kr",
    connectorId: "tiktok-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour * 5).toISOString(),
    endedAt: new Date(now - hour * 5 + 600).toISOString(),
    durationMs: 600,
    itemCount: 8,
    metadata: {},
  },
  {
    id: "log-006",
    jobId: "job-006",
    type: "channel",
    platform: "naver_blog",
    target: "blog_analytics_kr",
    connectorId: "naver_blog-crawler",
    status: "failed",
    errorMessage: "Crawler scaffold — pending implementation",
    userMessage: "네이버 블로그 크롤러가 아직 구현되지 않았습니다.",
    retryCount: 1,
    startedAt: new Date(now - hour * 6).toISOString(),
    endedAt: new Date(now - hour * 6 + 150).toISOString(),
    durationMs: 150,
    itemCount: 0,
    metadata: {},
  },
  {
    id: "log-007",
    jobId: "job-007",
    type: "mention",
    platform: "youtube",
    target: "브랜드 마케팅",
    connectorId: "youtube-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour).toISOString(),
    endedAt: new Date(now - hour + 550).toISOString(),
    durationMs: 550,
    itemCount: 3,
    metadata: {},
  },
  {
    id: "log-008",
    jobId: "job-008",
    type: "content",
    platform: "instagram",
    target: "ig_fashion_kr",
    connectorId: "instagram-mock",
    status: "success",
    errorMessage: null,
    userMessage: null,
    retryCount: 0,
    startedAt: new Date(now - hour * 0.5).toISOString(),
    endedAt: new Date(now - hour * 0.5 + 400).toISOString(),
    durationMs: 400,
    itemCount: 10,
    metadata: {},
  },
];

// ── Mock Connector Health Statuses ──

export const MOCK_CONNECTOR_HEALTH: ConnectorHealthStatus[] = [
  {
    connectorId: "youtube-api",
    platform: "youtube",
    sourceType: "api",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "API key not configured",
  },
  {
    connectorId: "youtube-mock",
    platform: "youtube",
    sourceType: "mock",
    healthy: true,
    latencyMs: 52,
    lastCheckedAt: new Date(now - 300000).toISOString(),
    message: "Mock 커넥터 정상 동작",
  },
  {
    connectorId: "instagram-api",
    platform: "instagram",
    sourceType: "api",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "Access token not configured",
  },
  {
    connectorId: "instagram-mock",
    platform: "instagram",
    sourceType: "mock",
    healthy: true,
    latencyMs: 48,
    lastCheckedAt: new Date(now - 300000).toISOString(),
    message: "Mock 커넥터 정상 동작",
  },
  {
    connectorId: "tiktok-api",
    platform: "tiktok",
    sourceType: "api",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "Access token not configured",
  },
  {
    connectorId: "x-api",
    platform: "x",
    sourceType: "api",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "Bearer token not configured",
  },
  {
    connectorId: "naver_blog-crawler",
    platform: "naver_blog",
    sourceType: "crawler",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "Crawler scaffold — pending implementation",
  },
  {
    connectorId: "news-crawler",
    platform: "news",
    sourceType: "crawler",
    healthy: false,
    latencyMs: null,
    lastCheckedAt: new Date(now - hour).toISOString(),
    message: "Crawler scaffold — pending implementation",
  },
];

// ── Mock Schedules ──

export const MOCK_SCHEDULES: CollectionSchedule[] = [
  {
    id: "sched-001",
    name: "YouTube 채널 스냅샷",
    type: "channel",
    platform: "youtube",
    targetId: "UC_mock_001",
    frequency: "daily",
    enabled: true,
    connectorPreference: "mock",
    lastCollectedAt: new Date(now - hour * 2).toISOString(),
    nextScheduledAt: new Date(now + hour * 22).toISOString(),
    createdAt: new Date(now - hour * 168).toISOString(),
    updatedAt: new Date(now - hour * 2).toISOString(),
  },
  {
    id: "sched-002",
    name: "YouTube 콘텐츠 수집",
    type: "content",
    platform: "youtube",
    targetId: "UC_mock_001",
    frequency: "every_6h",
    enabled: true,
    connectorPreference: "mock",
    lastCollectedAt: new Date(now - hour * 2).toISOString(),
    nextScheduledAt: new Date(now + hour * 4).toISOString(),
    createdAt: new Date(now - hour * 168).toISOString(),
    updatedAt: new Date(now - hour * 2).toISOString(),
  },
  {
    id: "sched-003",
    name: "Instagram 콘텐츠 수집",
    type: "content",
    platform: "instagram",
    targetId: "ig_brand_official",
    frequency: "every_12h",
    enabled: true,
    connectorPreference: "mock",
    lastCollectedAt: new Date(now - hour * 3).toISOString(),
    nextScheduledAt: new Date(now + hour * 9).toISOString(),
    createdAt: new Date(now - hour * 72).toISOString(),
    updatedAt: new Date(now - hour * 3).toISOString(),
  },
  {
    id: "sched-004",
    name: "키워드 멘션 수집",
    type: "mention",
    platform: "youtube",
    targetId: "소셜 분석",
    frequency: "hourly",
    enabled: true,
    connectorPreference: "mock",
    lastCollectedAt: new Date(now - hour).toISOString(),
    nextScheduledAt: new Date(now).toISOString(),
    createdAt: new Date(now - hour * 48).toISOString(),
    updatedAt: new Date(now - hour).toISOString(),
  },
  {
    id: "sched-005",
    name: "X 멘션 수집",
    type: "mention",
    platform: "x",
    targetId: "브랜드 마케팅",
    frequency: "every_6h",
    enabled: false,
    connectorPreference: "api",
    lastCollectedAt: null,
    nextScheduledAt: null,
    createdAt: new Date(now - hour * 24).toISOString(),
    updatedAt: new Date(now - hour * 24).toISOString(),
  },
  {
    id: "sched-006",
    name: "TikTok 콘텐츠 수집",
    type: "content",
    platform: "tiktok",
    targetId: "tiktok_brand_kr",
    frequency: "daily",
    enabled: true,
    connectorPreference: "mock",
    lastCollectedAt: new Date(now - hour * 5).toISOString(),
    nextScheduledAt: new Date(now + hour * 19).toISOString(),
    createdAt: new Date(now - hour * 48).toISOString(),
    updatedAt: new Date(now - hour * 5).toISOString(),
  },
];
