import type { Comment } from "./types";

// ============================================
// Mock Comments (30 comments across 5 platforms)
// ============================================

export const MOCK_COMMENTS: Comment[] = [
  // ---- YouTube ----
  {
    id: "cmt-yt-001",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c1",
    contentTitle: "2026 소셜미디어 트렌드 총정리",
    authorName: "김지현",
    authorProfileUrl: null,
    commentText:
      "영상 퀄리티가 점점 좋아지고 있어요! AI 트렌드 정리 최고입니다 👍",
    postedAt: "2026-03-07T08:30:00Z",
    likeCount: 42,
    replyCount: 2,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-yt-002",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c1",
    contentTitle: "2026 소셜미디어 트렌드 총정리",
    authorName: "tech_lover_99",
    authorProfileUrl: null,
    commentText: "구독료가 왜 이렇게 비싸요? 다른 채널은 무료인데...",
    postedAt: "2026-03-07T09:15:00Z",
    likeCount: 15,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-yt-003",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c2",
    contentTitle: "인스타그램 릴스 알고리즘 완전 분석",
    authorName: "마케터박",
    authorProfileUrl: null,
    commentText: "다음 라이브 일정이 언제예요? 기다리고 있어요!",
    postedAt: "2026-03-06T14:20:00Z",
    likeCount: 8,
    replyCount: 1,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-yt-004",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c3",
    contentTitle: "ChatGPT vs Claude 비교 리뷰",
    authorName: "angry_viewer",
    authorProfileUrl: null,
    commentText:
      "이건 완전 사기 아닌가요? 유료 멤버십 환불해주세요. 이런 식이면 고소할 겁니다.",
    postedAt: "2026-03-06T16:45:00Z",
    likeCount: 3,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-yt-005",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c3",
    contentTitle: "ChatGPT vs Claude 비교 리뷰",
    authorName: "AI_enthusiast",
    authorProfileUrl: null,
    commentText: "Claude가 확실히 더 나은 것 같아요. 좋은 비교 감사합니다!",
    postedAt: "2026-03-06T17:10:00Z",
    likeCount: 28,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-yt-006",
    platformCode: "youtube",
    channelId: "ch-yt-001",
    channelName: "TechInsight Korea",
    contentId: "c1",
    contentTitle: "2026 소셜미디어 트렌드 총정리",
    authorName: "spammer_bot",
    authorProfileUrl: null,
    commentText:
      "💰 하루 50만원 벌기! 이 링크 클릭하세요 → bit.ly/scam123 돈벌기 좋은 기회!",
    postedAt: "2026-03-07T02:00:00Z",
    likeCount: 0,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },

  // ---- Instagram ----
  {
    id: "cmt-ig-001",
    platformCode: "instagram",
    channelId: "ch-ig-001",
    channelName: "design.studio.kr",
    contentId: "c6",
    contentTitle: "UI 디자인 트렌드 2026",
    authorName: "design_min",
    authorProfileUrl: null,
    commentText: "디자인 퀄리티가 진짜 좋네요! 매번 영감을 받고 갑니다 ✨",
    postedAt: "2026-03-06T10:00:00Z",
    likeCount: 56,
    replyCount: 1,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-ig-002",
    platformCode: "instagram",
    channelId: "ch-ig-001",
    channelName: "design.studio.kr",
    contentId: "c7",
    contentTitle: "브랜딩 케이스 스터디 #12",
    authorName: "ux_learner",
    authorProfileUrl: null,
    commentText: "이 디자인 시스템 어떤 도구로 만드셨나요? Figma인가요?",
    postedAt: "2026-03-05T11:30:00Z",
    likeCount: 12,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-ig-003",
    platformCode: "instagram",
    channelId: "ch-ig-001",
    channelName: "design.studio.kr",
    contentId: "c9",
    contentTitle: "Figma 팁 모음 릴스",
    authorName: "frustrated_client",
    authorProfileUrl: null,
    commentText:
      "프로젝트 납기가 계속 늦어지고 있는데 어떻게 된 건가요? 연락도 안 되고 정말 실망입니다.",
    postedAt: "2026-03-04T09:00:00Z",
    likeCount: 5,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-ig-004",
    platformCode: "instagram",
    channelId: "ch-ig-001",
    channelName: "design.studio.kr",
    contentId: "c6",
    contentTitle: "UI 디자인 트렌드 2026",
    authorName: "color_palette",
    authorProfileUrl: null,
    commentText: "이 색상 조합 완벽해요! 어디서 참고하셨나요?",
    postedAt: "2026-03-06T14:20:00Z",
    likeCount: 22,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-ig-005",
    platformCode: "instagram",
    channelId: "ch-ig-001",
    channelName: "design.studio.kr",
    contentId: "c8",
    contentTitle: "디자인 시스템 구축 가이드",
    authorName: "newbie_designer",
    authorProfileUrl: null,
    commentText: "강의 가격이 궁금해요! 할인 코드 있나요?",
    postedAt: "2026-03-05T16:00:00Z",
    likeCount: 7,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },

  // ---- TikTok ----
  {
    id: "cmt-tt-001",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c10",
    contentTitle: "이 앱 알면 인생이 바뀜",
    authorName: "viral_watcher",
    authorProfileUrl: null,
    commentText: "대박 ㅋㅋㅋ 이거 진짜 신세계!! 바로 다운 받았어요",
    postedAt: "2026-03-07T12:00:00Z",
    likeCount: 234,
    replyCount: 5,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-tt-002",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c10",
    contentTitle: "이 앱 알면 인생이 바뀜",
    authorName: "skeptic_user",
    authorProfileUrl: null,
    commentText:
      "이거 광고 아닌가요? 솔직히 별로인데... 성능도 느리고 버그도 많고",
    postedAt: "2026-03-07T12:30:00Z",
    likeCount: 18,
    replyCount: 3,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-tt-003",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c11",
    contentTitle: "AI로 1분만에 영상 편집하기",
    authorName: "편집초보",
    authorProfileUrl: null,
    commentText: "이 앱 어떻게 다운받아요? 링크 알려주세요!",
    postedAt: "2026-03-06T10:00:00Z",
    likeCount: 45,
    replyCount: 1,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-tt-004",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c12",
    contentTitle: "직장인 필수 생산성 도구 TOP5",
    authorName: "office_hero",
    authorProfileUrl: null,
    commentText: "1번 도구 가격이 너무 비싸요 😢 무료 대안 없나요?",
    postedAt: "2026-03-05T14:00:00Z",
    likeCount: 67,
    replyCount: 2,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-tt-005",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c10",
    contentTitle: "이 앱 알면 인생이 바뀜",
    authorName: "happy_user",
    authorProfileUrl: null,
    commentText: "감사합니다! 정말 도움이 되었어요. 추천 최고! 🎉",
    postedAt: "2026-03-07T15:00:00Z",
    likeCount: 89,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-tt-006",
    platformCode: "tiktok",
    channelId: "ch-tt-001",
    channelName: "trend.hunter.kr",
    contentId: "c11",
    contentTitle: "AI로 1분만에 영상 편집하기",
    authorName: "rage_commenter",
    authorProfileUrl: null,
    commentText: "시발 이게 뭐야 돈 낭비시키는 거 아니냐 환불해라",
    postedAt: "2026-03-05T22:00:00Z",
    likeCount: 2,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },

  // ---- X ----
  {
    id: "cmt-x-001",
    platformCode: "x",
    channelId: "ch-x-001",
    channelName: "AI Daily News",
    contentId: "c13",
    contentTitle: "오늘의 AI 뉴스 브리핑 #234",
    authorName: "@ai_observer",
    authorProfileUrl: null,
    commentText: "매일 정리해주셔서 감사합니다. AI 업계 동향 파악에 최고예요!",
    postedAt: "2026-03-07T07:00:00Z",
    likeCount: 34,
    replyCount: 1,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-x-002",
    platformCode: "x",
    channelId: "ch-x-001",
    channelName: "AI Daily News",
    contentId: "c14",
    contentTitle: "GPT-5 출시 임박? 루머 정리",
    authorName: "@tech_critic",
    authorProfileUrl: null,
    commentText:
      "이 정보 출처가 어디인가요? 검증 안 된 루머를 확산시키는 건 문제가 있습니다.",
    postedAt: "2026-03-06T08:00:00Z",
    likeCount: 22,
    replyCount: 4,
    language: "ko",
    status: "reviewing",
  },
  {
    id: "cmt-x-003",
    platformCode: "x",
    channelId: "ch-x-001",
    channelName: "AI Daily News",
    contentId: "c14",
    contentTitle: "GPT-5 출시 임박? 루머 정리",
    authorName: "@daily_reader",
    authorProfileUrl: null,
    commentText: "다음 뉴스레터 발행 일정이 언제인가요?",
    postedAt: "2026-03-06T09:30:00Z",
    likeCount: 5,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-x-004",
    platformCode: "x",
    channelId: "ch-x-001",
    channelName: "AI Daily News",
    contentId: "c15",
    contentTitle: "AI 스타트업 투자 동향 스레드",
    authorName: "@venture_watcher",
    authorProfileUrl: null,
    commentText:
      "좋은 분석이네요. 한 가지 보완하면, 최근 시리즈 B 투자 규모가 전년 대비 30% 감소한 점도 포함하면 좋겠습니다.",
    postedAt: "2026-03-05T11:00:00Z",
    likeCount: 45,
    replyCount: 2,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-x-005",
    platformCode: "x",
    channelId: "ch-x-001",
    channelName: "AI Daily News",
    contentId: "c13",
    contentTitle: "오늘의 AI 뉴스 브리핑 #234",
    authorName: "@spam_account",
    authorProfileUrl: null,
    commentText:
      "FREE CRYPTO GIVEAWAY! Click link in bio 🚀🚀🚀 Don't miss out!!",
    postedAt: "2026-03-07T03:00:00Z",
    likeCount: 0,
    replyCount: 0,
    language: "en",
    status: "unanswered",
  },

  // ---- Custom ----
  {
    id: "cmt-cs-001",
    platformCode: "custom",
    channelId: "ch-custom-001",
    channelName: "Marketing Lab Blog",
    contentId: "c16",
    contentTitle: "2026 디지털 마케팅 전략 가이드",
    authorName: "marketer_kim",
    authorProfileUrl: null,
    commentText:
      "정말 유용한 가이드네요. 특히 SEO 전략 부분이 실무에 바로 적용 가능해서 좋았습니다.",
    postedAt: "2026-03-06T13:00:00Z",
    likeCount: 12,
    replyCount: 1,
    language: "ko",
    status: "responded",
  },
  {
    id: "cmt-cs-002",
    platformCode: "custom",
    channelId: "ch-custom-001",
    channelName: "Marketing Lab Blog",
    contentId: "c17",
    contentTitle: "SNS 광고 ROI 분석 방법론",
    authorName: "startup_ceo",
    authorProfileUrl: null,
    commentText: "컨설팅 서비스 가격이 궁금합니다. 문의 방법 알려주세요.",
    postedAt: "2026-03-05T10:00:00Z",
    likeCount: 3,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-cs-003",
    platformCode: "custom",
    channelId: "ch-custom-001",
    channelName: "Marketing Lab Blog",
    contentId: "c16",
    contentTitle: "2026 디지털 마케팅 전략 가이드",
    authorName: "competitor_spy",
    authorProfileUrl: null,
    commentText:
      "이 내용 대부분 다른 블로그에서 베낀 거 아닌가요? 출처도 없고... 이런 식이면 신고합니다.",
    postedAt: "2026-03-04T18:00:00Z",
    likeCount: 1,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
  {
    id: "cmt-cs-004",
    platformCode: "custom",
    channelId: "ch-custom-001",
    channelName: "Marketing Lab Blog",
    contentId: "c18",
    contentTitle: "콘텐츠 마케팅 성공 사례 5선",
    authorName: "content_fan",
    authorProfileUrl: null,
    commentText:
      "배송 관련 문의입니다. 주문한 자료집이 아직 도착하지 않았어요. 언제 배송되나요?",
    postedAt: "2026-03-03T09:00:00Z",
    likeCount: 0,
    replyCount: 0,
    language: "ko",
    status: "unanswered",
  },
];
